-- File contenente tutte le configurazioni DB

create sequence seq_ids;

create table usr_users (
    ID NUMBER(10,0) NOT NULL,
    USERNAME VARCHAR2(256 BYTE),
    VERSION NUMBER(10,0),
    FL_DELETED NUMBER(1,0),
    INSERT_DATE DATE,
    DELETION_DATE DATE,
    CONSTRAINT PK_USR_USERS PRIMARY KEY (ID)
);

create table lst_lists (
    ID NUMBER(10,0) NOT NULL,
    NAME VARCHAR2(256 BYTE),
    DESCRIPTION VARCHAR2(4000 BYTE),
    ID_TYPE NUMBER(10,0),
    ID_USER NUMBER(10,0),
    VERSION NUMBER(10,0),
    FL_DELETED NUMBER(1,0),
    INSERT_DATE DATE,
    DELETION_DATE DATE,
    CONSTRAINT PK_USR_USERS PRIMARY KEY (ID),
    CONSTRAINT FK_LST_LISTS_ID_TYPE FOREIGN KEY (ID_TYPE) REFERENCES lst_list_types(ID),
    CONSTRAINT FK_LST_LISTS_ID_USER FOREIGN KEY (ID_USER) REFERENCES usr_users(ID)
);

create table lst_list_types (
    ID NUMBER(10,0) NOT NULL,
    NAME VARCHAR2(256 BYTE),
    DESCRIPTION VARCHAR2(4000 BYTE),
    VERSION NUMBER(10,0),
    FL_DELETED NUMBER(1,0),
    INSERT_DATE DATE,
    DELETION_DATE DATE,
    CONSTRAINT PK_USR_USERS PRIMARY KEY (ID)
);